# Generated by Django 5.1.7 on 2025-04-01 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tickettransaction',
            name='pages_ticke_barcode_46907f_idx',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='barcode',
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='tickettransaction',
            index=models.Index(fields=['ticket_code'], name='pages_ticke_ticket__dd4372_idx'),
        ),
    ]
