# Generated by Django 5.1.7 on 2025-04-04 03:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_tickettransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettransaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Ticket Transaction', 'verbose_name_plural': 'Ticket Transactions'},
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When ticket was verified', null=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='date_completed',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='When transaction was initiated'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='is_checked_in',
            field=models.BooleanField(default=False, help_text='Whether ticket has been used for entry'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='paystack_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw payment data from Paystack'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Reference ID from Paystack', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Base64 encoded QR code image', null=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='ticket_code',
            field=models.CharField(blank=True, help_text='Unique ticket identifier for verification', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='tickettransaction',
            index=models.Index(fields=['is_checked_in'], name='pages_ticke_is_chec_fa1472_idx'),
        ),
    ]
